server:
  port: 8099
spring:
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false # OSIV 설정 끄기

management:
  endpoints:
    web:
      exposure:
        include: health  # 이 부분 추가
custom:
  prod:
    cookieDomain: pawpaw.kknaks.site
    frontUrl: "https://www.${custom.prod.cookieDomain}"
    backUrl: "https://api.${custom.prod.cookieDomain}"
  site:
    name: "pawpaw"
    cookieDomain: "${custom.prod.cookieDomain}"
    frontUrl: "${custom.prod.frontUrl}"
    backUrl: "${custom.prod.backUrl}"
services:
  auth:
    url: http://110.165.16.61:8090  # 인증 서비스 URL
  post:
    url: http://110.165.16.61:8093  # 게시글 서비스 URL
  chat:
    url: http://110.165.16.61:8095  # 채팅 서비스 URL
  noti:
    url: http://110.165.16.61:8097  # 알림 서비스 URL
  payment:
    url: http://110.165.16.61:8099 # 결제 서비스 URL
