server:
  port: 8100
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health  # 이 부분 추가
services:
  auth:
    url: http://172.30.1.23:8090 # 인증 서비스 URL
  post:
    url: http://172.30.1.23:8093  # 게시글 서비스 URL
  chat:
    url: http://172.30.1.23:8095  # 채팅 서비스 URL
  noti:
    url: http://172.30.1.23:8097  # 알림 서비스 URL
  payment:
    url: http://172.30.1.23:8100 # 결제 서비스 URL
  search:
    url: http://172.30.1.23:8103  # 검색 서비스 URL
  carecenter:
    url: http://172.30.1.23:8105 # 병원 서비스 URL
