server:
  port: 8100
spring:
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: dev
    include: secret
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB   # 개별 파일 최대 크기
      max-request-size: 100MB
logging:
  level:
    root: info
    com.ll.hereispaw : debug
    org.hibernate.spatial: debug

